version: '3.1'
services:
  db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sakuradb
      MYSQL_USER: sakura
      MYSQL_PASSWORD: sakura-internet